### ISSUE TITLE
Cannot find module 'jsonfile'

### ISSUE THREAD

**Issue by jiayisheji** [wpfpizicai/gulp-md5-plus#21]
Error: Cannot find module 'jsonfile'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\github\gulp-webpack-demo\node_modules\gulp-md5-plus\index.js:7:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by wpfpizicai** [comment]
npm install package jsonfile  before use gulp
